[project]
name = "board_game_graph"
version = "0.0.2"
description = "Represent games the most efficiently to draw 'play graphs'."
authors = [
    { name="Detroix23", email="detroix23@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]
dependencies = [
    "asttokens==3.0.2",
    "colorama==0.4.6",
    "decorator==5.3.1",
    "executing==2.2.1",
    "graphviz==0.21",
    "ipython==9.15.0",
    "ipython_pygments_lexers==1.1.1",
    "jedi==0.20.0",
    "Jinja2==3.1.6",
    "jsonpickle==4.1.2",
    "MarkupSafe==3.0.3",
    "matplotlib-inline==0.2.2",
    "networkx==3.6.1",
    "numpy==2.4.6",
    "parso==0.8.7",
    "prompt_toolkit==3.0.52",
    "psutil==7.2.2",
    "pure_eval==0.2.3",
    "Pygments==2.20.0",
    "pyvis==0.3.2",
    "stack-data==0.6.3",
    "traitlets==5.15.1",
    "wcwidth==0.8.2",
]

license = "CC-BY-4.0"
license-files = ["LICENSE.md"]

[project.urls]
Repository = "https://github.com/Detroix23/board_game_graph"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.mypy]
strict = true
